---
- name: 'Instala pacotes de dependencia para o sitema operacional'
  apt:
    name: 
      - php5
      - apache2
      - libapache2-mod-php5
      - php5-gd
      - libssh2-php
      - php5-mcrypt
      - python-mysqldb
      - php5-mysql
      - python3-pip
    state: latest
  become: yes